language: php
dist: trusty

matrix:
    include:
        - php: 7.2
          env: ILLUMINATE_VERSION=6.* TESTBENCH_VERSION=4.*
        - php: 7.3
          env: ILLUMINATE_VERSION=7.* TESTBENCH_VERSION=5.*
        - php: 7.3
          env: ILLUMINATE_VERSION=6.* TESTBENCH_VERSION=4.*
        - php: 7.4
          env: ILLUMINATE_VERSION=7.* TESTBENCH_VERSION=5.*
        - php: 7.4
          env: ILLUMINATE_VERSION=6.* TESTBENCH_VERSION=4.*

before_script:

before_install:
    - travis_retry composer self-update
    - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --dev
    - composer require "illuminate/database:${ILLUMINATE_VERSION}" --no-update
    - composer require "illuminate/support:${ILLUMINATE_VERSION}" --no-update

install: composer update --prefer-source --no-interaction

sudo: false

cache:
    directories:
        - $HOME/.composer/cache

script:
    - vendor/bin/phpunit
