language: php

php:
    - 7.2
    - 7.3
    - 7.4

env:
    - TESTBENCH_VERSION=4.*

before_install:
    - travis_retry composer self-update
    - composer require "orchestra/testbench:${TESTBENCH_VERSION}" --no-update --dev

install: composer update --prefer-source --no-interaction

sudo: true

cache:
    directories:
        - $HOME/.composer/cache

script:
    - vendor/bin/phpunit
